-- Audit columns are part of initial_schema.sql on the clean-rewrite branch.
-- Keep this changeSet as a no-op so fresh installs can apply the historical
-- sequence without trying to add already-present columns.
