spring:
  application:
    name: room-server
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/team-building/db.changelog-master.yaml

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      probes:
        enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:16:///test
    username: test
    password: test
