spring:
  application:
    name: fantazzk-server
  datasource:
    url: jdbc:postgresql://localhost:54322/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173

server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - loggers
  endpoint:
    health:
      probes:
        enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:16:///test
    username: test
    password: test

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    default-schema: dev

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    default-schema: production

cors:
  allowed-origins: []
