package com.naminhyeok.fantazzk.architecture

import liquibase.Contexts
import liquibase.LabelExpression
import liquibase.Liquibase
import liquibase.database.DatabaseFactory
import liquibase.database.jvm.JdbcConnection
import liquibase.resource.ClassLoaderResourceAccessor
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import java.sql.DriverManager
import java.util.UUID

class TemplateProjectionCleanupMigrationIntegrationTest {
    @Test
    fun `legacy template projection 테이블이 있어도 현재 changelog 를 적용할 수 있다`() {
        val jdbcUrl = "jdbc:tc:postgresql:16:///template_projection_cleanup_${UUID.randomUUID()}?TC_DAEMON=true"

        DriverManager.getConnection(jdbcUrl, "test", "test").use { connection ->
            connection.createStatement().use { statement ->
                statement.execute(
                    """
                    create table template_view (
                        template_id bigint primary key,
                        name varchar(255) not null,
                        mode varchar(32) not null,
                        team_count integer not null,
                        team_size integer not null,
                        budget integer,
                        draft_order_strategy varchar(32)
                    )
                    """.trimIndent(),
                )
                statement.execute(
                    """
                    create table template_player_view (
                        id bigint generated by default as identity primary key,
                        template_id bigint not null,
                        name varchar(255) not null,
                        display_order integer not null
                    )
                    """.trimIndent(),
                )
            }

            val database = DatabaseFactory.getInstance().findCorrectDatabaseImplementation(JdbcConnection(connection))
            Liquibase(
                "db/changelog/team-building/db.changelog-master.yaml",
                ClassLoaderResourceAccessor(),
                database,
            ).use { liquibase ->
                liquibase.update(Contexts(), LabelExpression())
            }
        }

        DriverManager.getConnection(jdbcUrl, "test", "test").use { verificationConnection ->
            assertThat(tableExists(verificationConnection, "template")).isTrue()
            assertThat(tableExists(verificationConnection, "template_player")).isTrue()
            assertThat(tableExists(verificationConnection, "template_view")).isFalse()
            assertThat(tableExists(verificationConnection, "template_player_view")).isFalse()
        }
    }

    private fun tableExists(
        connection: java.sql.Connection,
        tableName: String,
    ): Boolean =
        connection.metaData.getTables(null, null, tableName, arrayOf("TABLE")).use { tables ->
            tables.next()
        }
}
